# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle" 
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Ignore any versions for these libraries that don't match their specified versions
      - dependency-name: "heizi_flash_tools"
        versions: ["0.0.8"]
      - dependency-name: "ext-apk_parser"
        versions: ["0.0.1-alpha04"]
