# These are supported funding model platforms

github: ["ElisaMin"]
patreon: "Heizi"
# open_collective: # Replace with a single Open Collective username
ko_fi: "Heizi"
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: "Heizi"
issuehunt: "elisamin"
# otechie: # Replace with a single Otechie username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ["post-heizi.taobao.com","https://afdian.net/@heizi"]
